app:
    resource: "@AppBundle/Resources/config/routing.yml"

api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/routing-api.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc