app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "@AppBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc