api_book_list:
  path: /api/book/list
  defaults: { _controller: AppBundle:ApiBook:list }
  methods: GET

book_list:
  path: /books
  defaults: { _controller: AppBundle:Book:list }
  methods: GET

default:
  path: /
  defaults: { _controller: AppBundle:Default:index }
  methods: GET