services:
  book_service:
    class: AppBundle\Service\BookService
    arguments: [@doctrine]

  conection_service:
    abstract:  true
    class: AppBundle\Service\ConnectionService
    arguments: [@doctrine.dbal.default_connection]

  scrap_page_service:
    parent: conection_service
    class: AppBundle\Service\Scrap\PageScraper

  scrap_list_service:
    parent: conection_service
    class: AppBundle\Service\Scrap\ListScraper

  mesi.structure_service:
    parent: conection_service
    class: AppBundle\Service\MediaSite\StructureService

  mesi.analyze_structure_service:
    parent: conection_service
    class: AppBundle\Service\MediaSite\AnalyzeStructureService