services:
  book_service:
    class: AppBundle\Service\BookService
    arguments: [@doctrine]

  scrap_page_service:
    class: AppBundle\Service\Scrap\PageScraper
    arguments: [@doctrine.dbal.default_connection]

  scrap_list_service:
    class: AppBundle\Service\Scrap\ListScraper
    arguments: [@doctrine.dbal.default_connection]