AppBundle\Entity\Book:
  type: entity
  table: rr_book
  repositoryClass: AppBundle\Repository\BookRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    title:
      type: string
      length: 255
    description:
      type: string
      length: 255
    image:
      type: string